baseurl = "http://binarylogic.github.io/"
languageCode = "en-us"
disqusShortname = "binarylogicben"

[params]
Title = "Binary Logic"
Tagline = "Ben Johnson's personal engineering blog"
Author = "Ben Johnson"
Theme = "theme-binarylogic"
tagline = "Awesome tools and screencasts for Go programmers."
highlight = "github"
github = "github.com/binarylogic"
DateForm = "Monday, Jan 2, 2006"